### ISSUE TITLE
Move to an existing file error "is not an absolute path"

### ISSUE THREAD

**Issue by sumbatx15** [nicoespeon/abracadabra#376]
## Describe the bug

Im trying to move to an existing file, and I get an error message  "the path is not absolute"

## Expected behavior

should move code to an existing file

## Screenshots

![image](https://user-images.githubusercontent.com/28981577/131506896-30d72cdc-6584-4cad-966c-f50ae4450158.png)

## Additional information
Im using windows 10
and version v6.2.0
I tried with many other projects, and I still get this error message

**Comment by nicoespeon** [comment]
Thanks for reporting @sumbatx15, I'll take a look. I suspect this is because I did a mistake when determining if a path is absolute: doesn't seem to work fine with Windows ones 😅 

I'll get that fixed soon.

**Comment by nicoespeon** [comment]
While I can't reproduce on my side, I have a hypothesis: I'm using `path.sep` to determine the path separator per OS. So for Windows, it would be `\\`.

But since the code runs within VS Code, the paths may be normalized to use `/` instead. That's why the path appears with `/d:/WEB/` where I would expect `\D:\WEB\`. Thus, the logic fails to recognize the path.

I'm gonna bring a change to fix that. I'll need you to let me know if it's fixed.

**Comment by nicoespeon** [comment]
@sumbatx15 I published v6.3 which should fix the issue. Can you confirm?

**Comment by nicoespeon** [comment]
@all-contributors please add sumbatx15 for bugs

**Comment by sumbatx15** [comment]
> @sumbatx15 I published v6.3 which should fix the issue. Can you confirm?

Hi, thank you very much, love your work, I will confirm soon

**Comment by sumbatx15** [comment]
@nicoespeon Hi, I've checked, before 6.3.0 I couldn't even get the prompt for `"Search files by name and pick one"` with the files dropdown, now I get that, but when I'm choosing the file, I get the same error as before
I did a little bit of debugging, just a little bit :) and I found that when the extension searches for files to move to
we get the path with `/` separator
![searching file path separators](https://user-images.githubusercontent.com/28981577/132040610-4bf19fe2-e808-4ede-8a96-2e2179b9a8d7.png)

but in the `"Search files by name and pick one"` dropdown when I select, I get a different looking path with `\\` separator
![selecting file path separator](https://user-images.githubusercontent.com/28981577/132040744-60de3972-379d-4f07-a145-a9814562d865.png)

I didn't dig deeper, cuz it's a hard task :D 
I hope this is helpful
lmk if you need anything else

**Comment by nicoespeon** [comment]
Thanks, @sumbatx15 that's helpful!
I think I'll be able to fix it for good. I have a good hunch on what is the cause of this mismatch 👍 

I'll let you know once it's (presumably) fixed.

**Comment by nicoespeon** [comment]
@sumbatx15 I just released another update that, I think, should fix it. Maybe not. At least, it should support both `/` and `\\` to determine if the path is absolute. I _guess_ it should work fine but there may be another issue happening later in the process…

Please let me know when you have time to give it a try 😉

**Comment by sumbatx15** [comment]
@nicoespeon 
Hi, I tried and got another error 
![Screenshot_3](https://user-images.githubusercontent.com/28981577/132324207-3d86335d-2abb-4e06-bf62-3f16f5beb1ad.png)

I tried to run a path test in the extension and it failed

![image](https://user-images.githubusercontent.com/28981577/132327393-e73d405a-2709-4795-b81c-2f2bef5cb93a.png)

so I wrote a normalizer for the Path class, and seems like it works now on windows, I tested the extension, and indeed it is moving files, and I ran the test again and it passed :) 

![image](https://user-images.githubusercontent.com/28981577/132326568-047cb553-5cab-466c-91d7-14e01bceea84.png)

the thing is that vscode normalizes the path to use the `/` separator for any OS
but the path module is adapting to the OS and uses a different separator
so I added normalize on `relativeTo` and `absoluteFrom`  methods, because that's where the path is going from `/` to `\\`
here is the code, do whatever you want with it :)
Thank you and keep up to good work 
```typescript
import * as path from "path";

export { Path, AbsolutePath, RelativePath };

class Path {
  static separator = "/";
  static normalize(value: string): string {
    return value.replace(/\\/g, Path.separator);
  }

  constructor(protected _value: string) {}

  get value(): string {
    return Path.normalize(this._value.trim());
  }

  equals(otherValue: string): boolean {
    return this.value === otherValue;
  }

  get withoutExtension(): string {
    return this.value.replace(/\.\w+$/, "");
  }

  get fileName(): string {
    return path.basename(this.value);
  }

  get withoutFileName(): string {
    return path.dirname(this.value) + Path.separator;
  }

  protected get isValueAbsolute(): boolean {
    return this.value.startsWith(Path.separator);
  }

  relativeTo(otherPath: Path): RelativePath;
  relativeTo(value: string): RelativePath;
  relativeTo(pathOrValue: Path | string): RelativePath {
    const value =
      typeof pathOrValue === "string" ? pathOrValue : pathOrValue.value;

    const relativeValue = path.relative(path.dirname(value), this.value);
    return new RelativePath(Path.normalize(relativeValue));
  }
}

class AbsolutePath extends Path {
  constructor(value: string) {
    super(value);

    if (!this.isValueAbsolute) {
      throw new Error(`${value} is not an absolute path`);
    }
  }
}

class RelativePath extends Path {
  constructor(value: string) {
    super(value);

    if (this.isValueAbsolute) {
      throw new Error(`${value} is not a relative path`);
    }

    if (!this._value.startsWith(".")) {
      this._value = `.${Path.separator}${this._value}`;
    }
  }

  absoluteFrom(value: string): AbsolutePath {
    const absoluteValue = path.join(path.dirname(value), this.value);
    return new AbsolutePath(Path.normalize(absoluteValue));
  }
}
```

**Comment by sumbatx15** [comment]
@nicoespeon Hi bro, I still get errors, but I found a good solution to that
vscode is using `/` separator for any OS 
path module uses different separators for different OS
inside the path.ts you have 2 methods that changing the path separators because you're using `path.relative` and `path.join`
but you can make the path module consistent by using the `posix` module
take a look, 
https://nodejs.org/api/path.html#path_windows_vs_posix
`To achieve consistent results when working with POSIX file paths on any operating system, use path.posix:`
I ran a test on my end, and it works perfect, moves code to an existing file, and the path test is passing

**Comment by nicoespeon** [comment]
Oh, that's awesome! Thanks for your help debugging this 👍 

Would you like to open a PR with the change? Otherwise, I'll do the change on my side and push that this week, no worries.
